"""initial_schema

Revision ID: edc485ec639c
Revises:
Create Date: 2026-03-05 05:48:16.460907

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "edc485ec639c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("sku_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("brand", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("attributes_json", sa.JSON(), nullable=True),
        sa.Column(
            "source", sa.Enum("JSON", "CSV", "EXCEL", "ALGOLIA", name="sourceenum"), nullable=False
        ),
        sa.Column("source_snapshot_json", sa.JSON(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("sku_id"),
    )
    op.create_index("ix_products_category", "products", ["category"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "assignments",
        sa.Column("assignment_id", sa.UUID(), nullable=False),
        sa.Column("sku_id", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column(
            "assigned_role",
            sa.Enum("ADMIN", "REVIEWER_GENERAL", "REVIEWER_CATEGORY", name="roleenum"),
            nullable=False,
        ),
        sa.Column("assigned_to_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("OPEN", "IN_PROGRESS", "DONE", name="assignmentstatusenum"),
            nullable=False,
        ),
        sa.Column(
            "priority", sa.Enum("HIGH", "MEDIUM", "LOW", name="priorityenum"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_to_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["products.sku_id"],
        ),
        sa.PrimaryKeyConstraint("assignment_id"),
    )
    op.create_index(
        "ix_assignments_category_status_priority",
        "assignments",
        ["category", "status", "priority"],
        unique=False,
    )
    op.create_table(
        "audit_results",
        sa.Column("audit_id", sa.UUID(), nullable=False),
        sa.Column("sku_id", sa.String(), nullable=False),
        sa.Column("completeness_score", sa.Float(), nullable=False),
        sa.Column("richness_score", sa.Float(), nullable=False),
        sa.Column("missing_critical_fields", sa.JSON(), nullable=True),
        sa.Column("low_quality_fields", sa.JSON(), nullable=True),
        sa.Column(
            "priority_for_enrichment",
            sa.Enum("HIGH", "MEDIUM", "LOW", name="priorityenum"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["products.sku_id"],
        ),
        sa.PrimaryKeyConstraint("audit_id"),
    )
    op.create_index(
        "ix_audit_results_priority_created",
        "audit_results",
        ["priority_for_enrichment", "created_at"],
        unique=False,
    )
    op.create_table(
        "enrichment_versions",
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("sku_id", sa.String(), nullable=False),
        sa.Column("parent_version_id", sa.UUID(), nullable=True),
        sa.Column(
            "generated_by",
            sa.Enum("LLM", "HUMAN", "SYSTEM", name="generatedbyenum"),
            nullable=False,
        ),
        sa.Column("model_name", sa.String(), nullable=True),
        sa.Column("prompt_version", sa.String(), nullable=True),
        sa.Column("use_case_tags", sa.JSON(), nullable=True),
        sa.Column("persona_tags", sa.JSON(), nullable=True),
        sa.Column("trust_signals", sa.JSON(), nullable=True),
        sa.Column("agent_summary", sa.Text(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("evidence_fields", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_version_id"],
            ["enrichment_versions.version_id"],
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["products.sku_id"],
        ),
        sa.PrimaryKeyConstraint("version_id"),
    )
    op.create_index(
        "ix_enrichment_versions_sku_created",
        "enrichment_versions",
        ["sku_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "REVIEWER_GENERAL", "REVIEWER_CATEGORY", name="roleenum"),
            nullable=False,
        ),
        sa.Column("category", sa.String(), nullable=True),
        sa.CheckConstraint(
            "(role != 'REVIEWER_CATEGORY') OR (category IS NOT NULL)",
            name="ck_category_required_for_reviewer_category",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "role"),
    )
    op.create_table(
        "review_comments",
        sa.Column("comment_id", sa.UUID(), nullable=False),
        sa.Column("sku_id", sa.String(), nullable=False),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column(
            "comment_type",
            sa.Enum("NOTE", "PROMPT_FEEDBACK", "QUALITY_FLAG", name="commenttypeenum"),
            nullable=False,
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["products.sku_id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["enrichment_versions.version_id"],
        ),
        sa.PrimaryKeyConstraint("comment_id"),
    )
    op.create_table(
        "review_states",
        sa.Column("review_id", sa.UUID(), nullable=False),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column(
            "review_status",
            sa.Enum(
                "PENDING_REVIEW",
                "APPROVED",
                "REJECTED",
                "ESCALATED",
                "NEEDS_REVIEW",
                name="reviewstatusenum",
            ),
            nullable=False,
        ),
        sa.Column("reviewer_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column(
            "priority_for_review",
            sa.Enum("HIGH", "MEDIUM", "LOW", name="priorityenum"),
            nullable=True,
        ),
        sa.Column("escalated", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["enrichment_versions.version_id"],
        ),
        sa.PrimaryKeyConstraint("review_id"),
        sa.UniqueConstraint("version_id"),
    )
    op.create_index(
        "ix_review_states_status_created",
        "review_states",
        ["review_status", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_review_states_status_created", table_name="review_states")
    op.drop_table("review_states")
    op.drop_table("review_comments")
    op.drop_table("user_roles")
    op.drop_index("ix_enrichment_versions_sku_created", table_name="enrichment_versions")
    op.drop_table("enrichment_versions")
    op.drop_index("ix_audit_results_priority_created", table_name="audit_results")
    op.drop_table("audit_results")
    op.drop_index("ix_assignments_category_status_priority", table_name="assignments")
    op.drop_table("assignments")
    op.drop_table("users")
    op.drop_index("ix_products_category", table_name="products")
    op.drop_table("products")
    # ### end Alembic commands ###
